import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  doc, 
  getDocs, 
  setDoc, 
  deleteDoc, 
  query, 
  orderBy,
  Firestore,
  getDocFromServer,
  getDoc
} from 'firebase/firestore';
import { 
  getAuth, 
  signInWithEmailAndPassword, 
  createUserWithEmailAndPassword,
  signOut, 
  onAuthStateChanged, 
  Auth, 
  User,
  GoogleAuthProvider,
  signInWithPopup
} from 'firebase/auth';
import { Submission, SubmissionItem } from './types';

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

// Global variable holding the active configuration
let firebaseApp: FirebaseApp | null = null;
let firestoreDb: Firestore | null = null;
let firebaseAuth: Auth | null = null;
let currentUser: User | null = null;

// Helper to check and parse stored config
export const getStoredFirebaseConfig = (): any | null => {
  try {
    const localConfig = localStorage.getItem('NUSANTARA_FIREBASE_CONFIG');
    if (localConfig) {
      return JSON.parse(localConfig);
    }
  } catch (e) {
    console.warn('Failed to parse locally stored Firebase config:', e);
  }

  // Fallback to import.meta.env if provided at build-time
  const envConfig = import.meta.env.VITE_FIREBASE_CONFIG;
  if (envConfig) {
    try {
      return JSON.parse(envConfig);
    } catch {
      // If it's a string representation or individual variables fallback
    }
  }

  // Alternately check if any discrete env variables exist
  if (import.meta.env.VITE_FIREBASE_API_KEY) {
    return {
      apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
      authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
      storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: import.meta.env.VITE_FIREBASE_APP_ID
    };
  }

  // Static fallback: The user's production Firebase project
  return {
    apiKey: "AIzaSyDfIvUOLqAULR9eKy0rkqJfY_99Q4rxy2M",
    authDomain: "pencatatan-voucher-perusahaan.firebaseapp.com",
    databaseURL: "https://pencatatan-voucher-perusahaan-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "pencatatan-voucher-perusahaan",
    storageBucket: "pencatatan-voucher-perusahaan.firebasestorage.app",
    messagingSenderId: "5344554002",
    appId: "1:5344554002:web:9137a500fbb8f3223b7ccb",
    measurementId: "G-1249N852Y5"
  };
};

// TWO-WAY DATA SCHEMAS TRANSLATION / MAPPER UTILITIES
export const mapFirestoreToSubmission = (docId: string, data: any): Submission => {
  let firestoreItems = Array.isArray(data.items) ? data.items : [];
  
  // Reconstruct nested item array if the old record was stored flat at the top-level
  if (firestoreItems.length === 0) {
    const itemName = data.isi_invoice || data.isiInvoice || data.item || data.nama || data.jenis_pengajuan || data.jenisPengajuan || data.jenis || 'Item Penyerahan';
    const itemTotal = parseFloat(data.total_nominal || data.totalNominal || data.nominal || data.total || '0') || 0;
    const itemQty = data.qty !== undefined ? String(data.qty) : (data.jumlahVolume || '1');
    const itemKeterangan = data.no_invoice || data.noInvoice || data.keterangan || '';
    
    firestoreItems = [{
      id: `item-${docId}-flat`,
      no: 1,
      nama: itemName,
      qty: itemQty,
      nominal: itemTotal,
      totalNominal: itemTotal,
      noInvoice: itemKeterangan,
      keterangan: itemKeterangan,
      status: data.status || 'Belum Lunas'
    }];
  }

  // Map internal database nested maps to UI SubmissionItem structures
  const mappedItems: SubmissionItem[] = firestoreItems.map((fi: any, idx: number) => {
    let ket = '';
    if (fi.keterangan !== undefined) {
      ket = fi.keterangan || '';
    } else if (fi.noInvoice !== undefined) {
      const isAutoGenerated = typeof fi.noInvoice === 'string' && fi.noInvoice.startsWith('INV-sub-');
      ket = isAutoGenerated ? '' : (fi.noInvoice || '');
    }
    return {
      id: fi.id || `item-${docId}-${idx}-${Math.random().toString(36).substr(2, 4)}`,
      no: fi.no || (idx + 1),
      item: fi.nama || fi.item || 'Item Penyerahan',
      jumlahVolume: fi.qty !== undefined ? `${fi.qty}` : (fi.jumlahVolume || '1'),
      total: fi.totalNominal || fi.nominal || fi.total || 0,
      keterangan: ket
    };
  });

  // Extract date correctly from Firestore Timestamp, milliseconds, or string representation
  let createdAtStr = new Date().toISOString();
  const rawCreatedAt = data.createdAt || data.created_at || data.tanggal;
  if (rawCreatedAt) {
    if (typeof rawCreatedAt.toDate === 'function') {
      createdAtStr = rawCreatedAt.toDate().toISOString();
    } else if (rawCreatedAt.seconds) {
      createdAtStr = new Date(rawCreatedAt.seconds * 1000).toISOString();
    } else {
      createdAtStr = String(rawCreatedAt);
    }
  }

  // Determine which field holds the long document code (e.g. BKK-NMSA/VI/2026/10001)
  let docCode = '';
  const candidates = [
    data.no_invoice,
    data.noInvoice,
    data.kode,
    data.code
  ];
  for (const c of candidates) {
    if (typeof c === 'string' && c.length > 5) {
      docCode = c;
      break;
    }
  }
  if (!docCode) {
    docCode = data.no_invoice || data.noInvoice || data.kode || data.code || 'BKK-HO/VI/2026/10001';
  }

  const firstItem = firestoreItems[0] || {};
  const isDocLunas = data.status === 'Lunas' || firstItem.status === 'Lunas' || data.dibayarkanDengan === 'Cek/Transfer' || data.dibayarkan_dengan === 'Cek/Transfer';
  const finalStatus = data.status || firstItem.status || (isDocLunas ? 'Lunas' : 'Belum Lunas');

  return {
    id: docId,
    lokasi: data.lokasi || firstItem.lokasi || 'Lt. 1',
    tanggal: data.tanggal || data.tanggal_pengajuan || firstItem.tanggal || new Date().toISOString().split('T')[0],
    jenisPengajuan: data.jenisPengajuan || data.jenis_pengajuan || data.jenis || firstItem.jenis || 'Biaya Gaji',
    kode: docCode,
    dibayarkanKepada: data.dibayarkanKepada || data.dibayarkan_kepada || 'Penerima',
    dibayarkanDengan: data.dibayarkanDengan || data.dibayarkan_dengan || (finalStatus === 'Lunas' ? 'Cek/Transfer' : 'Tunai'),
    status: finalStatus as 'Lunas' | 'Belum Lunas',
    notes: data.notes || data.catatan || data.catatan_tambahan || data.catatanTambahan || '',
    
    // Corporate signatures support
    dibuatOleh: data.dibuatOleh || data.createdByEmail || 'Nur Wahyudi',
    disetujuiOleh: data.disetujuiOleh || 'Harijon',
    diverifikasiOleh: data.diverifikasiOleh || 'Andi Dhiya Salsabila',
    diverifikasiJabatan: data.diverifikasiJabatan || 'Keuangan',
    disetujuiOleh2: data.disetujuiOleh2 || 'H. A. Nursyam Halid',
    disetujuiJabatan2: data.disetujuiJabatan2 || 'Direktur Utama',
    dibukukanOleh: data.dibukukanOleh || 'Sri Ekowati',
    dibukukanJabatan: data.dibukukanJabatan || 'Accounting',

    // Google Drive attachment support
    googleDriveFileUrl: data.googleDriveFileUrl || '',
    googleDriveFileName: data.googleDriveFileName || '',
    googleDriveFiles: data.googleDriveFiles || (data.googleDriveFileUrl ? [{ url: data.googleDriveFileUrl, name: data.googleDriveFileName || 'Buka di Drive' }] : []),

    items: mappedItems,
    createdAt: createdAtStr
  };
};

export const mapSubmissionToFirestore = (
  sub: Submission, 
  userEmail?: string, 
  userId?: string,
  userCompanyId: string = 'nmsa',
  userCompanyName: string = 'PT Nusantara Mineral Sukses Abadi'
): any => {
  const finalStatus = sub.status || (sub.dibayarkanDengan === 'Cek/Transfer' ? 'Lunas' : 'Belum Lunas');
  const isLunas = finalStatus === 'Lunas';
  const computedTotal = sub.items.reduce((sum, item) => sum + item.total, 0);
  const firstItemKeterangan = sub.items[0]?.keterangan || '';
  const firstItemName = sub.items[0]?.item || '';

  let shortKode = 'HO';
  if (sub.kode) {
    const upperSubKode = sub.kode.toUpperCase();
    if (upperSubKode.includes('LP')) {
      shortKode = 'LP';
    } else if (upperSubKode.includes('HO')) {
      shortKode = 'HO';
    } else {
      shortKode = userCompanyId ? userCompanyId.toUpperCase() : 'HO';
    }
  }

  const cleanItems = sub.items.map((item, idx) => {
    // Extract numbers from volume (e.g. "1 Lot" -> 1, "5 Box" -> 5)
    const parsedQty = parseInt(item.jumlahVolume.replace(/[^0-9]/g, '')) || 1;
    
    return {
      nama: item.item,
      nominal: item.total, 
      qty: parsedQty,
      jenis: sub.jenisPengajuan,
      kode: shortKode,
      lokasi: sub.lokasi,
      noInvoice: item.keterangan || '',
      keterangan: item.keterangan || '',
      status: finalStatus,
      tanggal: sub.tanggal,
      tglBayar: isLunas && sub.tanggal ? new Date(sub.tanggal) : null,
      totalNominal: item.total
    };
  });

  return {
    // Both camelCase and snake_case fields for total backwards compatibility
    catatan: sub.notes || '',
    catatan_tambahan: sub.notes || '',
    catatanTambahan: sub.notes || '',
    companyId: userCompanyId,
    companyName: userCompanyName,
    company_id: userCompanyId,
    company_name: userCompanyName,
    createdAt: new Date(),
    created_at: new Date(),
    createdBy: userId || 'pwsDJv3bKHQamy89PDaAeCoZQcU2',
    createdByEmail: userEmail || 'admin@nmsa.com',
    dibayarkanKepada: sub.dibayarkanKepada,
    dibayarkan_kepada: sub.dibayarkanKepada,
    dibayarkanDengan: sub.dibayarkanDengan,
    dibayarkan_dengan: sub.dibayarkanDengan,
    status: finalStatus,
    totalNominal: computedTotal,
    total_nominal: computedTotal,
    noInvoice: sub.kode,
    no_invoice: sub.kode,
    isi_invoice: firstItemName,
    isiInvoice: firstItemName,
    files: [],
    
    // Google Drive attachment support
    googleDriveFileUrl: sub.googleDriveFileUrl || '',
    googleDriveFileName: sub.googleDriveFileName || '',
    googleDriveFiles: sub.googleDriveFiles || [],

    items: cleanItems,
    updatedAt: new Date(),
    updated_at: new Date(),
    
    // Double save native fields so pulling it back preserves signatures
    id: sub.id,
    lokasi: sub.lokasi,
    tanggal: sub.tanggal,
    jenisPengajuan: sub.jenisPengajuan,
    jenis_pengajuan: sub.jenisPengajuan,
    jenis: sub.jenisPengajuan,
    kode: shortKode,
    dibuatOleh: sub.dibuatOleh,
    disetujuiOleh: sub.disetujuiOleh,
    diverifikasiOleh: sub.diverifikasiOleh,
    diverifikasiJabatan: sub.diverifikasiJabatan,
    disetujuiOleh2: sub.disetujuiOleh2,
    disetujuiJabatan2: sub.disetujuiJabatan2,
    dibukukanOleh: sub.dibukukanOleh,
    dibukukanJabatan: sub.dibukukanJabatan
  };
};

export const getUserProfileFromFirestore = async (uid: string): Promise<any> => {
  if (!isFirebaseConfigured() || !firestoreDb) return null;
  try {
    const docRef = doc(firestoreDb, 'users', uid);
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      return snap.data();
    }
  } catch (err) {
    console.warn('Silent read rejection - failed to fetch user profile:', err);
  }
  return null;
};

export const getCompanyProfileFromFirestore = async (companyId: string): Promise<any> => {
  if (!isFirebaseConfigured() || !firestoreDb) return null;
  try {
    const docRef = doc(firestoreDb, 'companies', companyId.toLowerCase().trim());
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      return snap.data();
    }
  } catch (err) {
    console.warn('Silent read rejection - failed to fetch company profile:', err);
  }
  return null;
};

export const registerUserToFirebase = async (
  email: string, 
  password: string, 
  fullName: string, 
  role: string,
  companyId: string = 'nmsa',
  companyName: string = 'PT Nusantara Mineral Sukses Abadi'
): Promise<User> => {
  if (!firebaseAuth) {
    throw new Error('Firebase Auth is not initialized. Please configure credentials first.');
  }
  if (!firestoreDb) {
    throw new Error('Firestore is not initialized. Please configure credentials first.');
  }
  try {
    const creds = await createUserWithEmailAndPassword(firebaseAuth, email, password);
    const user = creds.user;
    
    // Wait for the auth session to populate, then record the user under users/
    await setDoc(doc(firestoreDb, 'users', user.uid), {
      uid: user.uid,
      email: user.email,
      fullName: fullName,
      role: role ?? 'User',
      companyId: companyId.toLowerCase().trim(),
      companyName: companyName,
      createdAt: new Date().toISOString()
    });

    // Check if the company document already exists; if not, create it with user provided/standard fallbacks
    const companyCleanId = companyId.toLowerCase().trim();
    const companyRef = doc(firestoreDb, 'companies', companyCleanId);
    const companySnap = await getDoc(companyRef);
    
    if (!companySnap.exists()) {
      await setDoc(companyRef, {
        id: companyCleanId,
        code: companyCleanId.toUpperCase(),
        name: companyName,
        fullName: companyName,
        defaultJenis: 'Operasional Kantor',
        defaultKode: `BKK-${companyCleanId.toUpperCase()}/V/2026/10001`,
        defaultLokasi: 'Lt.1',
        displayName: `Invoice-${companyCleanId.toUpperCase()}`,
        icon: '🏢',
        isActive: true,
        no_invoice_prefix: `BKK-${companyCleanId.toUpperCase()}`,
        sigAccounting: role.toLowerCase().includes('accounting') || role.toLowerCase().includes('finance') ? fullName : 'Sri Ekowati',
        sigDibuat: fullName || 'Nur Wahyudi',
        sigDirKeuangan: 'Harijon',
        sigDirektur: 'Andi Nursyam Halid',
        sigDisetujui: 'Harijon',
        sigKeuangan: 'Andi Dhiya Salsabila',
        updatedAt: new Date().toISOString()
      });
      console.log(`🏬 Company metadata workspace created for [${companyCleanId}]`);
    }

    return user;
  } catch (error: any) {
    console.error('Authentication Signup Failed:', error);
    throw error;
  }
};

// Initialize Firebase dynamically based on configs
export const initializeFirebaseApp = (customConfig?: any): boolean => {
  const config = customConfig || getStoredFirebaseConfig();
  if (!config || !config.apiKey || !config.projectId) {
    firebaseApp = null;
    firestoreDb = null;
    firebaseAuth = null;
    return false;
  }

  try {
    if (getApps().length > 0) {
      firebaseApp = getApp();
    } else {
      firebaseApp = initializeApp(config);
    }
    // Set firestore and auth instances
    firestoreDb = getFirestore(firebaseApp);
    firebaseAuth = getAuth(firebaseApp);
    
    // Register listener for auth states
    onAuthStateChanged(firebaseAuth, (user) => {
      currentUser = user;
      console.log('📡 Auth State Modified. User logged in:', user?.email || 'NONE');
    });

    console.log('✅ Firebase initialized successfully with project:', config.projectId);
    
    // Asynchronously validate connection to Firestore
    testConnection();
    return true;
  } catch (e) {
    console.error('❌ Failed to initialize Firebase:', e);
    firebaseApp = null;
    firestoreDb = null;
    firebaseAuth = null;
    return false;
  }
};

// Asynchronously validate connection
async function testConnection() {
  if (!firestoreDb) return;
  try {
    await getDocFromServer(doc(firestoreDb, 'test', 'connection'));
    console.log('📡 Firestore database connection status: ACTIVE');
  } catch (error) {
    if (error instanceof Error && error.message.includes('the client is offline')) {
      console.warn("Please check your Firebase configuration or network status.");
    }
  }
}

// Helper to check configuration readiness
export const isFirebaseConfigured = (): boolean => {
  if (!firestoreDb) {
    return initializeFirebaseApp();
  }
  return true;
};

// Custom Firestore standard error reporter
function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: currentUser?.uid || 'ANONYMOUS_CLIENT_DASHBOARD',
      email: currentUser?.email || null,
      emailVerified: currentUser?.emailVerified || null,
      isAnonymous: currentUser?.isAnonymous || true,
      tenantId: currentUser?.tenantId || null,
      providerInfo: currentUser?.providerData || []
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// Firebase Auth API Wrappers
export const loginToFirebase = async (email: string, password: string): Promise<User> => {
  if (!firebaseAuth) {
    throw new Error('Firebase Auth is not initialized. Please configure credentials first.');
  }
  try {
    const creds = await signInWithEmailAndPassword(firebaseAuth, email, password);
    currentUser = creds.user;
    return creds.user;
  } catch (error) {
    console.error('Authentication Failed:', error);
    throw error;
  }
};

export const logoutFromFirebase = async (): Promise<void> => {
  if (!firebaseAuth) return;
  await signOut(firebaseAuth);
  currentUser = null;
};

export const getFirebaseUser = (): User | null => {
  return currentUser;
};

export const registerAuthChangeListener = (callback: (user: User | null) => void): (() => void) => {
  if (!firebaseAuth) {
    return () => {};
  }
  return onAuthStateChanged(firebaseAuth, callback);
};

// ═════════ GOOGLE DRIVE / OAUTH PERSISTENCE UTILITIES ═════════
let googleDriveTokenMemory: string | null = null;

export const setGoogleDriveToken = (token: string | null) => {
  googleDriveTokenMemory = token;
  if (token) {
    localStorage.setItem('NUSANTARA_GOOGLE_DRIVE_TOKEN', token);
  } else {
    localStorage.removeItem('NUSANTARA_GOOGLE_DRIVE_TOKEN');
  }
};

export const getStoredGoogleDriveToken = (): string | null => {
  if (googleDriveTokenMemory) return googleDriveTokenMemory;
  try {
    return localStorage.getItem('NUSANTARA_GOOGLE_DRIVE_TOKEN');
  } catch {
    return null;
  }
};

export const googleDriveLogin = async (): Promise<{ user: User; accessToken: string }> => {
  if (!firebaseAuth) {
    throw new Error('Database autentikasi belum beroperasi.');
  }

  const provider = new GoogleAuthProvider();
  // Request Google Drive File write/edit permissions
  provider.addScope('https://www.googleapis.com/auth/drive.file');
  
  try {
    const result = await signInWithPopup(firebaseAuth, provider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    if (!credential?.accessToken) {
      throw new Error('Sesi otentikasi Google gagal menyuplai kunci akses (Access Token).');
    }
    
    setGoogleDriveToken(credential.accessToken);
    return { user: result.user, accessToken: credential.accessToken };
  } catch (error: any) {
    console.error('Error Google Drive connection:', error);
    throw error;
  }
};

// ═════════ FIRESTORE REST DATA OPERATION IMPLEMENTATIONS ═════════

// Fetch submissions from Firestore, optionally filtered by user's companyId to achieve database segregation
export const loadSubmissionsFromFirestore = async (companyId?: string): Promise<Submission[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    throw new Error('Firebase is not initialized. Please provide correct configuration.');
  }

  const path = 'submissions';
  try {
    const q = query(collection(firestoreDb, path), orderBy('tanggal', 'desc'));
    const snapshot = await getDocs(q);
    const list: Submission[] = [];
    
    snapshot.forEach(docSnap => {
      // Apply mapping from user schema (with items details and timestamps) to our rich interface
      const data = docSnap.data();
      const mapped = mapFirestoreToSubmission(docSnap.id, data);
      
      // Filter by companyId client-side to be 100% immune from missing index errors
      if (!companyId || data.companyId === companyId || data.company_id === companyId) {
        list.push(mapped);
      }
    });
    
    return list;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
    return [];
  }
};

// Put/Save single submission in Firestore under user's actual companyId
export const saveSubmissionToFirestore = async (
  submission: Submission, 
  userCompanyId: string = 'nmsa',
  userCompanyName: string = 'PT Nusantara Mineral Sukses Abadi'
): Promise<void> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    throw new Error('Firebase is not initialized.');
  }

  const path = `submissions`;
  try {
    // Map our rich React types to their exact expected database fields
    const fPayload = mapSubmissionToFirestore(
      submission, 
      currentUser?.email || 'admin@nmsa.com', 
      currentUser?.uid || 'pwsDJv3bKHQamy89PDaAeCoZQcU2',
      userCompanyId,
      userCompanyName
    );
    await setDoc(doc(firestoreDb, path, submission.id), fPayload);
    console.log(`☁️ Submission ${submission.id} mapped and saved in Firestore under company ${userCompanyId}.`);
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `${path}/${submission.id}`);
  }
};

// Delete single submission from Firestore
export const deleteSubmissionFromFirestore = async (id: string): Promise<void> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    throw new Error('Firebase is not initialized.');
  }

  const path = `submissions`;
  try {
    await deleteDoc(doc(firestoreDb, path, id));
    console.log(`☁️ Submission ${id} deleted from Firestore.`);
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `${path}/${id}`);
  }
};

// Set stored config dynamically (allows pasting from UI setting panel)
export const saveAndInitializeFirebaseConfig = (config: any): boolean => {
  if (!config || !config.apiKey || !config.projectId) {
    localStorage.removeItem('NUSANTARA_FIREBASE_CONFIG');
    firebaseApp = null;
    firestoreDb = null;
    firebaseAuth = null;
    return false;
  }

  localStorage.setItem('NUSANTARA_FIREBASE_CONFIG', JSON.stringify(config));
  return initializeFirebaseApp(config);
};

// Clear config to disconnect Firebase
export const clearFirebaseConfig = () => {
  localStorage.removeItem('NUSANTARA_FIREBASE_CONFIG');
  firebaseApp = null;
  firestoreDb = null;
  firebaseAuth = null;
};

// Load initial config checking
initializeFirebaseApp();

